export const rowData = [
  {
    team_name: 'Arsenal',
    overall_league_position: 1,
    overall_league_W: 10,
    overall_league_D: 5,
    overall_league_L: 3,
    overall_league_PTS: 35,
  },
  {
    team_name: 'Chelsea',
    overall_league_position: 2,
    overall_league_W: 9,
    overall_league_D: 6,
    overall_league_L: 3,
    overall_league_PTS: 33,
  },
  {
    team_name: 'Manchester United',
    overall_league_position: 3,
    overall_league_W: 8,
    overall_league_D: 7,
    overall_league_L: 3,
    overall_league_PTS: 31,
  },
  {
    team_name: 'Liverpool',
    overall_league_position: 4,
    overall_league_W: 8,
    overall_league_D: 6,
    overall_league_L: 4,
    overall_league_PTS: 30,
  },
  {
    team_name: 'Tottenhamspur',
    overall_league_position: 5,
    overall_league_W: 7,
    overall_league_D: 7,
    overall_league_L: 4,
    overall_league_PTS: 28,
  },
  {
    team_name: 'Everton',
    overall_league_position: 6,
    overall_league_W: 7,
    overall_league_D: 6,
    overall_league_L: 5,
    overall_league_PTS: 27,
  },
  {
    team_name: 'Leicester City',
    overall_league_position: 7,
    overall_league_W: 6,
    overall_league_D: 8,
    overall_league_L: 4,
    overall_league_PTS: 26,
  },
  {
    team_name: 'West Ham United',
    overall_league_position: 8,
    overall_league_W: 6,
    overall_league_D: 7,
    overall_league_L: 5,
    overall_league_PTS: 25,
  },
  {
    team_name: 'South',
    overall_league_position: 9,
    overall_league_W: 6,
    overall_league_D: 6,
    overall_league_L: 6,
    overall_league_PTS: 24,
  },
  {
    team_name: 'Wolverhampton Wanderers',
    overall_league_position: 10,
    overall_league_W: 5,
    overall_league_D: 8,
    overall_league_L: 5,
    overall_league_PTS: 23,
  },
  {
    team_name: 'Crystal Palace',
    _league_position: 11,
    overall_league_W: 5,
    overall_league_D: 7,
    overall_league_L: 6,
    overall_league_PTS: 22,
  },
  {
    team_name: 'Newcastle United',
    overall_league_position: 12,
    overall_league_W: 5,
    overall_league_D: 6,
    overall_league_L: 7,
    overall_league_PTS: 21,
  },
  {
    team_name: 'Brighton & Hove Albion',
    overall_league_position: 13,
    overall_league_W: 4,
    overall_league_D: 8,
    overall_league_L: 6,
    overall_league_PTS: 20,
  },
  {
    team_name: 'Burnley',
    overall_league_position: 14,
    overall_league_W: 4,
    overall_league_D: 7,
    overall_league_L: 7,
    overall_league_PTS: 19,
  },
  {
    _name: 'Fulham',
    overall_league_position: 15,
    overall_league_W: 3,
    overall_league_D: 9,
    overall_league_L: 6,
    overall_league_PTS: 18,
  },
  {
    team_name: 'West Bromwich Albion',
    overall_league_position: 16,
    overall_league_W: 3,
    overall_league_D: 8,
    overall_league_L: 7,
    overall_league_PTS: 17,
  },
  {
    team_name: 'Sheffield United',
    overall_league_position: 17,
    overall_league_W: 3,
    overall_league_D: 7,
    overall_league_L: 8,
    overall_league_PTS: 16,
  },
  {
    team_name: 'Aston Villa',
    overall_league_position: 18,
    overall_league_W: 3,
    overall_league_D: 6,
    overall_league_L: 9,
    overall_league_PTS: 15,
  },
  {
    team_name: 'Brentford',
    overall_league_position: 19,
    overall_league_W: 2,
    overall_league_D: 8,
    overall_league_L: 8,
    overall_league_PTS: 14,
  },
  {
    team_name: 'Norwich',
    overall_league_position: 20,
    overall_league_W: 2,
    overall_league_D: 6,
    overall_league_L: 10,
    overall_league_PTS: 12,
  },
];
